# Generated by Django 3.2.5 on 2021-08-13 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApplyMentoring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '멘토링 신청 내역',
                'verbose_name_plural': '멘토링 신청 내역',
                'db_table': 'apply_mentoring_table',
            },
        ),
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='칼럼 제목')),
                ('content', models.TextField(verbose_name='칼럼 내용')),
                ('photo', models.ImageField(blank=True, upload_to='', verbose_name='첨부 이미지')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성 날짜/시간')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='칼럼 수정일')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='칼럼 공개일')),
            ],
            options={
                'verbose_name': '칼럼',
                'verbose_name_plural': '칼럼',
                'db_table': 'column_table',
            },
        ),
        migrations.CreateModel(
            name='ColumnComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='댓글 내용')),
                ('commented_at', models.DateTimeField(auto_now_add=True, verbose_name='작성 날짜/시간')),
            ],
            options={
                'verbose_name': '칼럼 댓글',
                'verbose_name_plural': '칼럼 댓글',
                'db_table': 'column_comment_table',
            },
        ),
        migrations.CreateModel(
            name='DetailLecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_title', models.CharField(max_length=256, verbose_name='영상 제목')),
                ('url', models.CharField(max_length=256, verbose_name='url')),
            ],
            options={
                'verbose_name': '세부 강의',
                'verbose_name_plural': '세부 강의',
                'db_table': 'detail_lecture_table',
            },
        ),
        migrations.CreateModel(
            name='EventApply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='신청 날짜/시간')),
                ('agreement', models.BooleanField(default=False, verbose_name='정보제공 동의')),
                ('eventapply_content', models.CharField(blank=True, max_length=1600, verbose_name='이벤트지원서 내용')),
            ],
            options={
                'verbose_name': '이벤트신청',
                'verbose_name_plural': '이벤트신청',
                'db_table': 'EventApply_table',
            },
        ),
        migrations.CreateModel(
            name='EventList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='이벤트 제목')),
                ('event_content', models.TextField(blank=True, null=True, verbose_name='내용')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성 날짜/시간')),
                ('event_photo', models.ImageField(blank=True, upload_to='', verbose_name='첨부 이미지')),
            ],
            options={
                'verbose_name': '이벤트',
                'verbose_name_plural': '이벤트',
                'db_table': 'EventList_table',
            },
        ),
        migrations.CreateModel(
            name='FavouriteLecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '즐겨찾기 강의',
                'verbose_name_plural': '즐겨찾기 강의',
                'db_table': 'favourite_lecture_table',
            },
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture_title', models.CharField(max_length=256, verbose_name='강의 이름')),
                ('mentor_description', models.CharField(max_length=64, verbose_name='멘토 설명')),
                ('description', models.CharField(max_length=1000, verbose_name='설명')),
                ('price', models.CharField(max_length=64, verbose_name='가격')),
                ('field', models.CharField(blank=True, choices=[('IT/SW', 'IT/SW'), ('PM', 'PM'), ('건설/기계/기술', '건설/기계/기술'), ('광고/홍보', '광고/홍보'), ('금융/은행/보험', '금융/은행/보험'), ('디자인', '디자인'), ('미디어', '미디어'), ('연구개발', '연구개발'), ('유통/물류/무역', '유통/물류/무역'), ('인사총무', '인사총무'), ('품질', '품질'), ('의료', '의료'), ('영업/고객상담', '영업/고객상담'), ('생산제조', '생산제조'), ('마케팅/기획', '마케팅/기획'), ('경영/사무/행정', '경영/사무/행정'), ('MD/상품기획', 'MD/상품기획'), ('SCM', 'SCM'), ('기타', '기타')], max_length=64, null=True, verbose_name='분야')),
            ],
            options={
                'verbose_name': '전체 강의',
                'verbose_name_plural': '전체 강의',
                'db_table': 'lecture_table',
            },
        ),
        migrations.CreateModel(
            name='Mentor_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contents', models.TextField(default='(주)멋사', verbose_name='멘토 이력')),
                ('one_info', models.TextField(blank=True, null=True, verbose_name='멘토의 다짐')),
                ('field', models.CharField(choices=[('IT/SW', 'IT/SW'), ('PM', 'PM'), ('건설/기계/기술', '건설/기계/기술'), ('광고/홍보', '광고/홍보'), ('금융/은행/보험', '금융/은행/보험'), ('디자인', '디자인'), ('미디어', '미디어'), ('연구개발', '연구개발'), ('유통/물류/무역', '유통/물류/무역'), ('인사총무', '인사총무'), ('품질', '품질'), ('의료', '의료'), ('영업/고객상담', '영업/고객상담'), ('생산제조', '생산제조'), ('마케팅/기획', '마케팅/기획'), ('경영/사무/행정', '경영/사무/행정'), ('MD/상품기획', 'MD/상품기획'), ('SCM', 'SCM'), ('기타', '기타')], default='기타', max_length=128, verbose_name='멘토 직무')),
            ],
            options={
                'verbose_name': '멘토',
                'verbose_name_plural': '멘토',
                'db_table': 'mentor_table',
            },
        ),
        migrations.CreateModel(
            name='Mentoring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='멘토링 이름')),
                ('image', models.ImageField(blank=True, upload_to='', verbose_name='관련 이미지')),
            ],
            options={
                'verbose_name': '멘토링',
                'verbose_name_plural': '멘토링',
                'db_table': 'mentoring_table',
            },
        ),
        migrations.CreateModel(
            name='MyLecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'My 강의',
                'verbose_name_plural': 'My 강의',
                'db_table': 'mylecture_table',
            },
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('self_introduction_file', models.FileField(blank=True, null=True, upload_to='', verbose_name='자기소개서 파일')),
                ('self_introduction_name', models.CharField(blank=True, max_length=64, null=True, verbose_name='자기소개서 파일이름')),
                ('self_introduction_check', models.BooleanField(default=False, verbose_name='자기소개서 공개 비공개')),
                ('certificate', models.TextField(blank=True, verbose_name='자격증')),
                ('certificate_verify', models.ImageField(blank=True, upload_to='', verbose_name='자격증 이미지')),
                ('activity', models.TextField(blank=True, verbose_name='인턴, 대외활동')),
                ('language', models.TextField(blank=True, verbose_name='어학')),
                ('language_verify', models.CharField(blank=True, max_length=1600000, verbose_name='어학 취득번호')),
                ('language_score', models.TextField(blank=True, verbose_name='어학 점수')),
                ('prize', models.TextField(blank=True, max_length=16000000, verbose_name='수상실적')),
            ],
            options={
                'verbose_name': '스펙',
                'verbose_name_plural': '스펙',
                'db_table': 'qualification_table',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='질문 제목')),
                ('content', models.TextField(verbose_name='질문 내용')),
                ('photo', models.ImageField(blank=True, upload_to='', verbose_name='첨부 이미지')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성 날짜/시간')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='질문 수정일')),
            ],
            options={
                'verbose_name': '질문',
                'verbose_name_plural': '질문',
                'db_table': 'question_table',
            },
        ),
        migrations.CreateModel(
            name='QuestionComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='댓글 내용')),
                ('commented_at', models.DateTimeField(auto_now_add=True, verbose_name='작성 날짜/시간')),
            ],
            options={
                'verbose_name': '질문 댓글',
                'verbose_name_plural': '질문 댓글',
                'db_table': 'question_comment_table',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=1600, verbose_name='작성내용')),
                ('reivew_at', models.DateTimeField(auto_now_add=True, verbose_name='작성 날짜/시간')),
                ('review_point', models.IntegerField(blank=True, choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True, verbose_name='평점')),
            ],
            options={
                'verbose_name': '후기',
                'verbose_name_plural': '후기',
                'db_table': 'Review_table',
            },
        ),
    ]
